USE dev_cookhome;

INSERT INTO direction (tempo, timeunity, description, recipe_id) VALUES 
('25', 'Minutos', 'Amasse as bananas e acrescente a aveia, misturando bem. Depois, faça bolinhas no formato de pequenos biscoitos e coloque para assar em uma forma untada por 15 minutos em forno pré-aquecido a 175 graus. Se você quiser, também pode adicionar uma pitada de canela em pó, um punhadinho de frutos secos — como nozes e amêndoas, por exemplo — ou gotinhas de chocolate para incrementar as bolachas.','1' ),
('10', 'Minutos', 'Bata o ovo e amasse a banana. Junte a banana ao ovo em uma vasilha e mexa até dar liga. Adicione a canela. Acenda o fogo em temperatura média e adicione o óleo em uma frigideira grande. Com uma concha coloque a massa na frigideira formando círculos e frite dos dois lados.','2'),
('40', 'Minutos', 'Em uma tigela, misture a farinha e o iogurte; misture a massa até formar uma bola. Coloque a massa em uma superfície enfarinhada e deixe sovar por 5-8 minutos. Com um rolo de macarrão, deixe a massa em formato de pizza e depois adicione as coberturas. Pré-aqueça o forno. Coloque a pizza no forno em temperatura máxima por 12 minutos.', '3'),
('15', 'Minutos', 'Coloque a margarina dentro de uma panela e deixe ela derreter. Adicione o chocolate. Junte o leite condensado e mexa até formar uma calda grossa. Deixe esfriar por alguns minutos e sirva.', '4'),
('15', 'Minutos', 'Basta misturar o coco ralado com o leite condensado e colocar bolinhas com a ajuda de uma colher em uma forma forrada com papel manteiga. Depois, leve para assar em um forno pré-aquecido a 180 graus por 10 ou 12 minutos ou até que as bolinhas fiquem levemente douradas.', '5'),
('20', 'Minutos', 'Forre uma forma de 20 × 20 com papel manteiga. Coloque o chocolate em banho-maria em fogo baixo e mexa constantemente, até que o chocolate esteja completamente derretido. Transfira o chocolate para uma tigela à prova de calor e esfrie por 5 minutos. Adicione as Oreos picadas e misture bem. Despeje a mistura na tigela e use uma espátula para alisar topo. Pique as Oreos restantes e polvilhe por cima. Leve à geladeira por cerca de 10 minutos até que o chocolate endureça. Desenforme e sirva em cortes quadrados.','6'),
('25', 'Minutos', 'Amasse até soltar das mãos (caso precise um pouquinho a mais de polvilho, coloque aos poucos até que chegue ao ponto de enrolar). Faça bolinhas, coloque em forma untada e asse em forno pré-aquecido bem quente. Se achar necessário, acrescente sal. Asse até ficarem douradinhos levemente.','7'),
('10', 'Minutos', 'Coloque os ingredientes em um processador e bata até que os ingredientes formem uma massa. Isso deve acontecer depois de 2 minutos. Coloque um parte da massa em um pedaço de filme plástico, embrulhe e leve à geladeira por pelo menos uma hora ou durante a noite. Retire a massa da geladeira e corte em pequenos quadrados e guarde na geladeira para conservar.','8'),
('35', 'Minutos', 'Bata os ovos inteiros por cerca de 6 minutos até que eles tripliquem de tamanho. Depois, coloque a Nutella em um recipiente de vidro e leve ao micro-ondas por aproximadamente 20 segundos para deixar a consistência mais fluida. Então, acrescente ⅓ da nutella aos ovos batidos misturando bem, e vá fazendo o mesmo com as duas outras partes até que todo o chocolate seja incorporado. Despeje a mistura em uma forma redonda forrada com papel manteiga untado, e coloque para assar em forno pré-aquecido a 175 graus por 20 ou 25 minutos (ou verifique com um palito se a torta já está assada). Só desenforme depois de completamente fria.', '9'),
('20', 'Minutos', 'Misture os ingredientes em uma tigela grande até que a massa esteja lisa. Despeje em uma assadeira untada e leve ao forno pré-aquecido a 180ºC. Asse por aproximadamente 15 minutos ou até que o palito espetado na massa saia limpo. Deixe esfriar, corte e sirva.','10');